# 1Password secret references — safe to commit.
# Run with:  op run --env-file=.env.tpl -- <your command>
# Generated by credential audit 2026-07-30; refs are PREDICTED and
# must be confirmed with ./verify-op-refs.sh before deleting .env.

CLIENT_ID=op://Knoxx Foods/cartoncloud-knoxx-api/client id
CLIENT_SECRET=op://Knoxx Foods/cartoncloud-knoxx-api/client secret

# Test fixture IDs
TEST_TENANT_ID=b0407a72-99b2-4849-bbfb-b3279f1cee2e
TEST_CUSTOMER_ID=a4a6e109-2a33-4417-ad8e-9f1b1e7441ec
TEST_PRODUCT_ID=da3a7f89-2c97-44d9-96dc-cb43190291fe
TEST_ORDER_ID=6548072f-fd24-4b0c-8d08-8879a297eb99
